### ISSUE TITLE
Launching the app and putting it to background in quick succession leaves the app in splash fragment

### ISSUE THREAD

**Issue by kriticalflare** [Zhuinden/Jetpack-Navigation-Fragment-NavGraph-Dagger-SavedStateHandle-FTUE-Experiment#5]
Pressing home or recents button as soon as app starts and then later opening the app again leaves the app stuck in splash fragment 

![ezgif-3-eabfabea99da](https://user-images.githubusercontent.com/42350771/83868824-2ac18c00-a749-11ea-8abc-7c6e23b13388.gif)

Moving https://github.com/Zhuinden/jetpack-navigation-ftue-sample/blob/3ffdd6d695471ca7b2d99d510fd146f74eabce84/app/src/main/java/com/zhuinden/jetpacknavigationdaggersavedstatehandleftueexperiment/features/splash/SplashFragment.kt#L43 to onResume seems like a fix for this issue

**Comment by Zhuinden** [comment]
WOW. Makes sense, they are ignoring the navigation event after `onStateSaved()`.

Thanks I hate it XD i have to move it to `onStart`/`onStop`, then it would work.

I'm used to simple-stack enqueueing this instead of consuming it. 

Will fix in a moment, thanks for the notice!
